version: "3.8"

volumes:
  cluster_postgres_data: {}
  
services:
  services-cluster:
    container_name: microservices-cluster
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - cluster_postgres_data:/var/lib/postgresql/data